import earring from "../assets/earring.png";
import jhumka from "../assets/jhumka.png";
import jhumkaset from "../assets/jhumka box.png";
import studs from "../assets/studs.png";

export const dummyProducts = [
  {
    _id: "1",
    name: "Oxidised Earrings",
    price: 999,
    images: [earring],
    description: "Traditional oxidised earrings.",
    category: { name: "Jewellery" },
    collection: "new",
    stock: 20,
  },
  {
    _id: "2",
    name: "Bareilly Jhumka",
    price: 1499,
    images: [jhumka],
    description: "Classic jhumka design.",
    category: { name: "Jewellery" },
    collection: "best",
    stock: 15,
  },
  {
    _id: "3",
    name: "Jhumka Set",
    price: 1999,
    images: [jhumkaset],
    description: "Complete festive jhumka set.",
    category: { name: "Jewellery" },
    collection: "seasonal",
    stock: 10,
  },
  {
    _id: "4",
    name: "Studs",
    price: 799,
    images: [studs],
    description: "Elegant everyday studs.",
    category: { name: "Jewellery" },
    collection: "new",
    stock: 25,
  },
  {
    _id: "5",
    name: "Royal Jhumka",
    price: 1799,
    images: [jhumka],
    description: "Premium festive jhumka.",
    category: { name: "Jewellery" },
    collection: "best",
    stock: 12,
  },
  {
    _id: "6",
    name: "Festive Earrings",
    price: 1299,
    images: [earring],
    description: "Perfect for wedding season.",
    category: { name: "Jewellery" },
    collection: "seasonal",
    stock: 18,
  },
  {
    _id: "7",
    name: "Oxidised Earrings",
    price: 999,
    images: [earring],
    description: "Traditional oxidised earrings.",
    category: { name: "Jewellery" },
    collection: "new",
    stock: 20,
  },
  {
    _id: "8",
    name: "Bareilly Jhumka",
    price: 1499,
    images: [jhumka],
    description: "Classic jhumka design.",
    category: { name: "Jewellery" },
    collection: "best",
    stock: 15,
  },
  {
    _id: "9",
    name: "Jhumka Set",
    price: 1999,
    images: [jhumkaset],
    description: "Complete festive jhumka set.",
    category: { name: "Jewellery" },
    collection: "seasonal",
    stock: 10,
  },
  {
    _id: "10",
    name: "Studs",
    price: 799,
    images: [studs],
    description: "Elegant everyday studs.",
    category: { name: "Jewellery" },
    collection: "new",
    stock: 25,
  },
  {
    _id: "11",
    name: "Royal Jhumka",
    price: 1799,
    images: [jhumka],
    description: "Premium festive jhumka.",
    category: { name: "Jewellery" },
    collection: "best",
    stock: 12,
  },
  {
    _id: "12",
    name: "Festive Earrings",
    price: 1299,
    images: [earring],
    description: "Perfect for wedding season.",
    category: { name: "Jewellery" },
    collection: "seasonal",
    stock: 18,
  },
  {
    _id: "13",
    name: "Oxidised Earrings",
    price: 999,
    images: [earring],
    description: "Traditional oxidised earrings.",
    category: { name: "Jewellery" },
    collection: "new",
    stock: 20,
  },
  {
    _id: "14",
    name: "Bareilly Jhumka",
    price: 1499,
    images: [jhumka],
    description: "Classic jhumka design.",
    category: { name: "Jewellery" },
    collection: "best",
    stock: 15,
  },
  {
    _id: "15",
    name: "Jhumka Set",
    price: 1999,
    images: [jhumkaset],
    description: "Complete festive jhumka set.",
    category: { name: "Jewellery" },
    collection: "seasonal",
    stock: 10,
  },
  {
    _id: "16",
    name: "Studs",
    price: 799,
    images: [studs],
    description: "Elegant everyday studs.",
    category: { name: "Jewellery" },
    collection: "new",
    stock: 25,
  },
  {
    _id: "17",
    name: "Royal Jhumka",
    price: 1799,
    images: [jhumka],
    description: "Premium festive jhumka.",
    category: { name: "Jewellery" },
    collection: "best",
    stock: 12,
  },
  {
    _id: "18",
    name: "Festive Earrings",
    price: 1299,
    images: [earring],
    description: "Perfect for wedding season.",
    category: { name: "Jewellery" },
    collection: "seasonal",
    stock: 18,
  },
];
